In [1]:
import sys
import numpy as np

In [2]:
arr = np.array([0, 0.7, 0.5, 1.9, 7.1, .2])

In [3]:
print(arr)

[0.  0.7 0.5 1.9 7.1 0.2]


In [7]:
arr[-1]

0.2

In [9]:
arr[2::-1]

array([0.5, 0.7, 0. ])

In [10]:
arr[2:-1]

array([0.5, 1.9, 7.1])

In [11]:
arr[2::]

array([0.5, 1.9, 7.1, 0.2])

In [12]:
arr2 = arr[[0, 3, -1]]

In [13]:
arr2

array([0. , 1.9, 0.2])