In [23]:
from sklearn import preprocessing

In [24]:
labelEnc = preprocessing.LabelEncoder()

In [25]:
feature_data = [100, 200, 300, 400, 600, 500, 10, 1000, 100, 300, 25]

In [26]:
labelEnc.fit(feature_data)

LabelEncoder()

In [27]:
x = labelEnc.transform(feature_data)

In [28]:
x

array([2, 3, 4, 5, 7, 6, 0, 8, 2, 4, 1], dtype=int64)

In [29]:
labelEnc.inverse_transform(x)

array([ 100,  200,  300,  400,  600,  500,   10, 1000,  100,  300,   25])

In [30]:
feature_data = ['Kolkata', 'Bangalore', 'Delhi', 'Mumbai', 'Hyderabad']

In [31]:
labelEnc.fit(feature_data)

LabelEncoder()

In [32]:
y = labelEnc.transform(feature_data)

In [33]:
y

array([3, 0, 1, 4, 2], dtype=int64)

In [35]:
labelEnc.inverse_transform(y)

array(['Kolkata', 'Bangalore', 'Delhi', 'Mumbai', 'Hyderabad'],
      dtype='<U9')

In [36]:
data = [[11, 2], [3, 7], [0, 10], [11, 8]]

In [37]:
scaler = preprocessing.MinMaxScaler()

In [38]:
model = scaler.fit(data)

In [39]:
scaled_data = scaler.transform(data)

In [40]:
scaled_data

array([[1.        , 0.        ],
       [0.27272727, 0.625     ],
       [0.        , 1.        ],
       [1.        , 0.75      ]])

In [41]:
scaler.inverse_transform(scaled_data)

array([[11.,  2.],
       [ 3.,  7.],
       [ 0., 10.],
       [11.,  8.]])

In [42]:
std_scaler = preprocessing.StandardScaler()

In [43]:
model = std_scaler.fit(data)

In [44]:
scaled_data = std_scaler.transform(data)

In [45]:
scaled_data

array([[ 0.97596444, -1.61155897],
       [-0.66776515,  0.08481889],
       [-1.28416374,  1.10264561],
       [ 0.97596444,  0.42409446]])

In [46]:
data = ['cold', 'cold', 'warm', 'cold', 'hot', 'hot', 'warm', 'cold', 'warm', 'hot']

In [54]:
lEnc = preprocessing.LabelEncoder()
oneHenc = preprocessing.OneHotEncoder(sparse=False)

In [55]:
int_encoded = lEnc.fit_transform(data)

In [56]:
int_encoded

array([0, 0, 2, 0, 1, 1, 2, 0, 2, 1], dtype=int64)

In [57]:
int_encoded = int_encoded.reshape(len(int_encoded), 1)

In [58]:
int_encoded

array([[0],
       [0],
       [2],
       [0],
       [1],
       [1],
       [2],
       [0],
       [2],
       [1]], dtype=int64)

In [59]:
oneH_encoded = oneHenc.fit_transform(int_encoded)

In [60]:
oneH_encoded

array([[1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.]])